version: '3.8'

services:
  app:
    build: .
    ports:
      - "5050:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./downloads:/app/downloads
    environment:
      - DATABASE_URL=postgres://video_portgresql_db_user:${POSTGRES_PASSWORD}@db:5432/video_portgresql_db
      - REDIS_URL=redis://redis:6379

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=video_portgresql_db
      - POSTGRES_USER=video_portgresql_db_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  db_data: