version: '3.8'

services:
  app:
    build: .
    ports:
      - 5050:5000
    environment:
      - DATABASE_URL= #postgres://user:password@host:port/database
      - REDIS_URL= #redis://host:port
    depends_on:
      - db
      - redis
    volumes:
      - ./downloads:/app/downloads
    
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB= #database name
      - POSTGRES_USER= #database user
      - POSTGRES_PASSWORD= #database password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: 
      - "6379:6379"

volumes:
  db_data: