services:
  - type: web
    name: video-downloader
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    startCommand: gunicorn app:app --bind 0.0.0.0:5000
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis  
          name: video_downloader_redis
          property: connectionString
      - key: COOKIES_CONTENT
        value: "# Netscape HTTP Cookie File\n# Add your actual cookies here"

  - type: redis
    name: video_downloader_redis
    plan: free
    maxmemoryPolicy: allkeys-lru