services:
  - type: web
    name: video-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    region: oregon  # or frankfurt, singapore, etc.
    plan: free