name: Keep Render App Alive

on: 
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping Render App
      id: ping
      run: |
        if curl -s --max-time 5 https://video-download-o0wf.onrender.com > /dev/null; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=fail" >> $GITHUB_OUTPUT
        fi

    - name: Send Telegram alert if failed
      if: steps.ping.outputs.status == 'fail'
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="⚠️ Render app is NOT responding at https://video-download-o0wf.onrender.com"

          